### ISSUE TITLE
Broken Acceptance Tests

### ISSUE THREAD

**Issue by mbfrahry** [HewlettPackard/oneview-golang#94] opened 2016-10-27 20:08 UTC
1) ov/api_version_test:52 Should be true

2) ov/logical_interconnect_group_test:197 The \"type\" field content, \"logical-interconnect-groupV3\", included in this request is invalid.\n Response Status: 400 Bad Request"

3) ov/logical_interconnect_group_test:245 Not equal: "go LIG test" (expected)  != "" (actual)
//Because of 2

4) ov/logical_switch_group_test:62 400 Bad Request

5) ov/logical_switch_group_test:115 Not equal: "test logical switch group" (expected)  != "" (actual)
//Because of 4

6)ov/power_state_test:30 404 Not Found

7) ov/power_state_test:31 Not equal

8) ov/power_state_test:36 Not equal

9) ov/profile_templates_test:70 "goTestSPT" (expected) != "" (actual) //make sure it's actually being created

10) ov/profiles_test:96 Not equal: "wenlock-machine-1" (expected) != "" (actual)

11) ov/profiles_test:134 "Error connection not found on server profile, please try a different connection name."
//Because of 10

12) ov/profiles_test:135  Not equal: "AA:43:83:10:00:BA" (expected) != "null" (actual)
//Because of 10 

13) ov/profiles_test:157  Not equal: "VCGM123023" (expected) != "null" (actual)
//Because of 10

14) ov/server_hardware_test:30 404 not found

15) ov/server_hardware_test:32  "VCGM123023" (expected) != "null" (actual)
//Because of 14

16) ov/server_hardware_test:53 "Error! No available blades that are compatible with the server profile!"

17) ov/server_hardware_test:57 Should not be: ""

18) ov/server_hardware_test:79 404 not found

19) icsp/icsp_test:180 Error interface slotid not found please try another interface id."

20) icsp/icsp_test:181 "AA:43:83:10:00:BB" (expected) != "" (actual)
//Because of 19

21) icsp/icsp_test:184 404 not found

22) icsp/icsp_test:186 404 not found

23) icsp/icsp_test:194 public_interface for VCGM123023 Should have a value
//Because of 22

24) icsp/icsp_test:242 404 not found

25) icsp/icsp_test:296 404 not found

26) icsp/netwconfig_test:142 404 not found

27) icsp/servers_test:36 "Error public_interface custom attribute is not found."

28) icsp/servers_test:38 Should return an ip address string
// Because of 27

29) icsp/servers_test:79 "Error interface not found, please try a different mac address."

30 icsp/servers_test:80 "AA:43:83:10:00:BB" (expected)    != "" (actual)
// Because of 29

31) icsp/servers_test:120 Failed to get a valid list of interfaces -> []
// Because of 29

32) icsp/servers_test:174 "Error interface slotid not found please try another interface id."

33) icsp/servers_test:175 Failed to get a an interface name
// Because of 32

34) icsp/servers_test:179 Error interface slotid not found
// Because of 32

35)  icsp/servers_test:180 Failed to get interface name
// Because of 32

36) icsp/servers_test:221 404 Not Found

37) icsp/servers_test:269 "IC04-HOUEGSL-C7000-04-4" (expected) != "" (actual)
// Because of 36

38) icsp/servers_test:325 Should be true 

39) icsp/servers_test:326 500 server error

40) icsp/servers_test:348 Should be true

41) icsp_servers_test:372 404 not found

**Comment by AsisBagga** [comment] 2020-07-02 13:13
We have ran all the test locally and none of them failed as such. It looks to me that the issue is already been addressed. Hence closing it.

**Closed by AsisBagga** 2020-07-02 13:13 UTC
